# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2020-01-30 06:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0002_auto_20200130_0552'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='title',
        ),
        migrations.AddField(
            model_name='car',
            name='name',
            field=models.CharField(choices=[(0, 'Unknown'), (1, 'displayed'), (2, 'paid')], default='Enter Car name', max_length=36, unique=True),
        ),
    ]
