# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2020-01-30 06:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0003_auto_20200130_0611'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='bought',
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='car',
            name='description',
            field=models.TextField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='car',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='Carimage/'),
        ),
        migrations.AddField(
            model_name='car',
            name='is_used',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='car',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='car',
            name='name',
            field=models.CharField(choices=[(0, 'Unknown'), (1, 'displayed'), (2, 'paid')], max_length=36, null=True, unique=True),
        ),
    ]
